In [8]:
counter=100
distance=1000.0
name="Python dersı"
soz="Bugün'Yapay Zeka' dersi aldım" #çift tırnak içinde özel belirtmek istediğim
print(counter,distance,name,soz)

100 1000.0 Python dersı Bugün'Yapay Zeka' dersi aldım


In [18]:
str='Hello World!' # zero based indexing(bir dizinin ilk elemanı gibi)
print(str)# str yazdrma
print(str[0]) #noktalı virgül normalde ayıraç olarak kullanılmaz.
print(str); print(str[0])#noktalı virgül sayesinde printler yanyana yazılır.
print(str[2:5]) #2. indexi al 5.indexi alma.
print(str[2:])#gizli bir len fonksiyonu var gibi düşünebilirsin.
print(len(str)) #lenght(uzunluk)fonksiyonu
print(str*2) #bir str yi iki kere yazdırma (operand*int tekrarsayısı) 
print(str+"TEST") #string concatenation

Hello World!
H
Hello World!
H
llo
llo World!
Hello World!Hello World!
Hello World!TEST


In [19]:
list=['abcd',786,2.23,'Bill',70.2] #liste metodunun içinde çeşitli değişken tipleri yer alabilir.
miniList=[123,'Bİll']
print(list)
print(list[0])
print(list[1:3])
print(list[2:])
print(miniList*2)
print(list+miniList)

['abcd', 786, 2.23, 'Bill', 70.2]
abcd
[786, 2.23]
[2.23, 'Bill', 70.2]
[123, 'Bİll', 123, 'Bİll']
['abcd', 786, 2.23, 'Bill', 70.2, 123, 'Bİll']


In [27]:
print(17/3) #kalansız bölme
print(17//3.0) #kalanlı bölme,kalan 2
print(round(17/3))
print(2**7) #üs alma
17%3 #mod alma




5.666666666666667
5.0
6
128


2

In [28]:
width=20
height=5*9
print(width*height)

900


In [33]:
a=6
b=7
print(1, not a ==7 and b==7)
print(2, a ==7 or b ==6)
print(3, a ==7 or b ==6)
print(4, not (a ==7 and b ==6))
print(5, not (a ==7 and b ==6))

"""
AND Gate 
0 0|0
0 1|0
1 0|0
1 1|1

OR Gate
0 0|0
0 1|1
1 0|1
1 1|1

NOT Gate
0|1
1|0

XOR Gate
a b z
0 0|0
0 1|1
1 0|1
0 0|0


"""


1 True
2 False
3 False
4 True
5 True


'\nAND Gate \n0 0|0\n0 1|0\n1 0|0\n1 1|1\n\nOR Gate\n0 0|0\n0 1|1\n1 0|1\n1 1|1\n\nNOT Gate\n0|1\n1|0\n\nXOR Gate\na b z\n0 0|0\n0 1|1\n1 0|1\n0 0|0\n\n\n'

In [36]:
print('a > b is: ',  a>b)
print('a < b is :',  a<b)
print('a == b is :', a==b)
print('a != b is :', a!=b)
print('a >= b is :', a>=b)
print('a <= b is:',  a<=b)

a > b is:  False
a < b is : True
a == b is : False
a != b is : True
a >= b is : False
a <= b is: True


In [37]:
string1=" abc def ghi"
string2=" def ghi abc"
print(string1==string2) #stringlerin eşit olupolmadığını kıyaslama
print(string1!=string2)

False
True


In [38]:
s1="Mary"
s2="Mark"
print(s1<s2) #ASCII değer karşılaştırması kullanılır. 
#str karşılaştırma tablosundan yararlanılır.
#y,121; k,107 tablodaki değerleridir. 121< 107 (false)tüm değerlere göre toplar ve kıyaslar.


False


# if-elif-else

In [45]:
number=int(input("Bir sayı giriniz:"))
if number == 1 : #indentation çok önemli
    print('One')
    
else:
    if number == 2:
        print('Two')
        
    else:
        if number ==3 :
            print('Three')
        else:
            print('Unknown')
    

Bir sayı giriniz:1
One


In [47]:
number=int(input("Bir sayı giriniz:"))
if  number == 1:
    print('One')
elif  number == 2:
    print('Two')
elif  number == 3:
    print('Three')  
else :
    print('Unknown')

Bir sayı giriniz:45
Unknown


In [51]:
name=input("What is your name?")
password=int(input("What is the password?"))
if name =="ŞEVVAL HATİCE" and password==1352:
    print("Welcome to the hell")
elif name=="programming" and password ==6578:
    print("Welcome Miss.Programming'")
else:
    print("Sisteme tanımlı değilsiniz.")

What is your name?cffre
What is the password?gtg4r


ValueError: invalid literal for int() with base 10: 'gtg4r'

In [54]:
x=0.6
y=0.3
print(0.0 <= x <= 0.5)
print(0.5>= y >= 0.1)


False
True


In [56]:
num=100 #TAB DOWN KOD OKUMA
if num <=200:
    print("Bu ifade doğru!")
    print(num)
elif num==100:
    print("Bu ifade DE doğru!") # ilk kodu gerçekleştirdikten sonra bu kodu basmaz
    print(num)
else :
    print("Bu ifade doğru değil!")
    print(num)
print("Güle Güle !!!")

Bu ifade doğru!
100
Güle Güle !!!


# Döngüler,Tekrarlı Yapılar

In [60]:
#while True:
    print("sonsuza kadar") #interrupt the kernel,spyderda ctrl+c

IndentationError: unexpected indent (<ipython-input-60-e15763750eeb>, line 2)

In [1]:
import cmath #kompleks sayılar için matematiksel fonksiyon
complex_num=cmath.sqrt(-1) #spyderda ctrl+c sonsuz döngüden çıkma kodu
while complex_num:
    print(complex_num) #sonuz döngü oluşturma

1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1j
1

KeyboardInterrupt: 

# while koşul kontrollü döngü

In [68]:
count= 0 #preprocessing
while count  < 9 :
    print(f'The count is {count}')
    count=count +1
print('GOOD BYE ')
    

The count is 0
The count is 1
The count is 2
The count is 3
The count is 4
The count is 5
The count is 6
The count is 7
The count is 8
GOOD BYE 


#while-else

In [69]:
mycount=0
while mycount<5:
    print(mycount,"is less than 5")
    mycount+=1 #mycount=mycount+1
else:
    print(mycount,"is not less than 5")

0 is less than 5
1 is less than 5
2 is less than 5
3 is less than 5
4 is less than 5
5 is not less than 5


In [72]:
range(5)
#range(0,5)

range(0, 5)

In [76]:
list=[*range(1,10,2)] 
print(list)

[1, 3, 5, 7, 9]


In [79]:
#list(range(1,10,2)) spyder a bas.
for i in range(5,10):
    print(i)

5
6
7
8
9


In [ ]:
fruits=['banana','apple','mango']
for index in range(len(fruits)): #for döngüsünde hep hedef değişken vardır.
    print('Current fruit:',fruits[index])
print("Good Bye")

In [84]:
num_students=int(input("Kaç öğrenciniz var?"))
num_test_scores=int(input("Öğrenci başına kaç test var?"))
for student in range(num_students):
    total=0.0
    
    print('Student number',student+1)
    print('****')
    
    for test_num in range(num_test_scores):
        print('Test number',test_num+1,end='')
        score=float(input(':'))
        total+=score #aac(elde ettiğimiz skorları akümülatöre ekledik.) e skorları ekleme
    #ortalama hesabı
    average=total/num_test_scores
    print('Öğrenci {} için ortalama'.format(student+1),'is:',average)
    

Kaç öğrenciniz var?2
Öğrenci başına kaç test var?2
Student number 1
****
Test number 1:26
Test number 2:58
Öğrenci 1 için ortalama is: 42.0
Student number 2
****
Test number 1:30
Test number 2:50
Öğrenci 2 için ortalama is: 40.0


In [86]:
#for else
for i in range(3):
    print(i)
else:
    print("done")

0
1
2
done


In [10]:
for x in range(1,11):
    for y in range(1,11):
        print('%d * %d =%d' % (x,y,x*y))
        print(  )#%d ler decimal

1 * 1 =1

1 * 2 =2

1 * 3 =3

1 * 4 =4

1 * 5 =5

1 * 6 =6

1 * 7 =7

1 * 8 =8

1 * 9 =9

1 * 10 =10

2 * 1 =2

2 * 2 =4

2 * 3 =6

2 * 4 =8

2 * 5 =10

2 * 6 =12

2 * 7 =14

2 * 8 =16

2 * 9 =18

2 * 10 =20

3 * 1 =3

3 * 2 =6

3 * 3 =9

3 * 4 =12

3 * 5 =15

3 * 6 =18

3 * 7 =21

3 * 8 =24

3 * 9 =27

3 * 10 =30

4 * 1 =4

4 * 2 =8

4 * 3 =12

4 * 4 =16

4 * 5 =20

4 * 6 =24

4 * 7 =28

4 * 8 =32

4 * 9 =36

4 * 10 =40

5 * 1 =5

5 * 2 =10

5 * 3 =15

5 * 4 =20

5 * 5 =25

5 * 6 =30

5 * 7 =35

5 * 8 =40

5 * 9 =45

5 * 10 =50

6 * 1 =6

6 * 2 =12

6 * 3 =18

6 * 4 =24

6 * 5 =30

6 * 6 =36

6 * 7 =42

6 * 8 =48

6 * 9 =54

6 * 10 =60

7 * 1 =7

7 * 2 =14

7 * 3 =21

7 * 4 =28

7 * 5 =35

7 * 6 =42

7 * 7 =49

7 * 8 =56

7 * 9 =63

7 * 10 =70

8 * 1 =8

8 * 2 =16

8 * 3 =24

8 * 4 =32

8 * 5 =40

8 * 6 =48

8 * 7 =56

8 * 8 =64

8 * 9 =72

8 * 10 =80

9 * 1 =9

9 * 2 =18

9 * 3 =27

9 * 4 =36

9 * 5 =45

9 * 6 =54

9 * 7 =63

9 * 8 =72

9 * 9 =81

9 * 10 =90

10 * 1 =10

10 * 2 =20



In [20]:
#nested while loop
x=-20
y=20
while x<= y:
    print("X is now ",x)
    x+=1
    while x<0:
        print("X is negative",x)
        x+=1

X is now  -20
X is negative -19
X is negative -18
X is negative -17
X is negative -16
X is negative -15
X is negative -14
X is negative -13
X is negative -12
X is negative -11
X is negative -10
X is negative -9
X is negative -8
X is negative -7
X is negative -6
X is negative -5
X is negative -4
X is negative -3
X is negative -2
X is negative -1
X is now  0
X is now  1
X is now  2
X is now  3
X is now  4
X is now  5
X is now  6
X is now  7
X is now  8
X is now  9
X is now  10
X is now  11
X is now  12
X is now  13
X is now  14
X is now  15
X is now  16
X is now  17
X is now  18
X is now  19
X is now  20


In [ ]:
for i in range(2):
    print(i)
    if i==1:
        break
else:
    print("done")

# fonksiyonlar

In [25]:
#function definition
def myprint(str): 
    print(str)
    return
#definition call
myprint("Sevval") 
myprint("Hatıce")

Sevval
Hatıce


In [27]:
def Fun(x,y):
    result=x+y
    return result
print (Fun(5,43))

48


In [32]:
#fonksiyonlar içine listeyi argüman olarak ekleme.
def ChangeRefer(myList):
    myList=[2,4,5,7]
    print("First values:", myList)
myList=[10,20,30,40] #mutable 
ChangeRefer(myList)
print("Secondary values:", myList)
print(myList)


First values: [2, 4, 5, 7]
Secondary values: [10, 20, 30, 40]
[10, 20, 30, 40]


In [35]:
def printInfo(name,age=23): #değer atanmamış argüman,değer atanmış argüman
    print("Name:",name)
    print("Age:",age)
printInfo(age=19,name="Tasmanian Devil")
printInfo(name="Bugs Bunny") #default değer atanır.

Name: Tasmanian Devil
Age: 19
Name: Bugs Bunny
Age: 23


In [36]:
from random import randint # random fonksiyonunu çağırma.
print(randint(0,100))

import random #random modülünü çağırma
print(random.randint(0,100))


60
46


In [39]:
import random
print("randrange(100,1000,2):",random.randrange(100,1000,2)) 
print("Random Float uniform(19,38):",random.uniform(19,38)) #gerçek bir değer istediğimizde uniform fonks çağırılır.

randrange(100,1000,2): 836
Random Float uniform(19,38): 34.051538413423714


#fonksiyonu modül içinden çağırma
"""import sys            #system modülü
print(sys.path) #dizinle alakalı bilgilere erişirim.

from math import pi
print(pi)
"""

In [2]:
import math #math modülünü çağırır.
def area_of_circle(r): 
    a=r**2*math.pi
    return a
print(area_of_circle(3))

28.274333882308138


In [ ]:
#dosya açma
f=open("test.txt","w") #(file,mode)w--> dosyayı yazma izni ile açtım.
f.write("Now is the time")
f.write("to close the file.") 
f.close() #kodla dosya açtığında kodla kapatman lazım.
"""
f=open("test.txt","r") #okuma izni verdim.
text=f.read() #fonksiyona değer atamadığımdan hepsini okur.
print(text)
"""
"""
f=open("test.txt","r") #r open fonksiyonunun argümanıdır.
print(f.read(8)) #okuma kısmı kapandı,ilk 5 değeri okur
print(f.read(1000006)) #end of the file
"""
fo=open("foo.txt","w")
fo.write("Python is a great language.\nYeah it is great!!\n")
fo=open("foo.txt","r+") #r+ yazma izni extended reading
str=fo.read(17)
print("Our string is:",str)
position=fo.tell()
print("Current file position:",position) #imlecin hangi pozisyonda kaldığını öğrenmek
position=fo.seek(0,0) #0 ıncı pozisyona dönüş
str=fo.read(17)
print("Again our string is :",str)
fo.close()


In [ ]:
#Error
try: #try kısmında hata var.
    fh=open("testfile","r") #yazma izni verilmedi.
    fh.write("This is my test file for exception handling!")
except IOError: #kod problem üretmiş except çalışmış!
    print("Error:can\'t find file or read data") #escape parameter
else:
    print("Written content in the file succesfully.")

In [5]:
try:
    fh=open("testfile","w")
    fh.write("This is my test file for exception handling!")
finally: #hangi şartta olursa olsun.Yazma modunda okuma iznim olmasa da çalıştırmasını sağladı.
    print("Error:can\'t find file or read data")

Error:can't find file or read data


In [27]:
list=['chemistry','math','2089','23.45']
print("Value available at index 2:",list[2]) #zero-based indexing

del list[1]
print(list)



Value available at index 2: 2089
['chemistry', '2089', '23.45']


In [19]:
tup1=('chemistry','math','2089','23.45')
tup2=(1,2,3,4,5,6,7,8)
print("tup1[3]",tup1[3])
print("tup2[2:6]",tup2[2:6])

tup1[3] 23.45
tup2[2:6] (3, 4, 5, 6)


In [30]:
#değişken değiştirme
list=['geometry','biology',2022,32.34]
print(list[3])
list[3]='truth'
print(list)

32.34
['geometry', 'biology', 2022, 'truth']


In [31]:
#split
txt='Dream until your dreams come true'
words=txt.split()
print(words)

['Dream', 'until', 'your', 'dreams', 'come', 'true']


In [34]:
#list comprehensions
pow2=[2 ** x for x in range(10) if x>5]
print(pow2)
"""
pow2=[] #boş liste tanımlama
for x in range(10):
    pow2.append(print(2**x))
    """

[64, 128, 256, 512]


In [46]:
langs=[]
langs.append('Python')
langs.append('Perl')
print(langs)
langs.insert(0,"PHP") #index,atanacak değer.
langs.insert(2,"Lua") 
print(langs)
langs.extend(("Actionscript","Javascript")) #extend() takes exactly one argument (2 given)
print(langs)
print(langs.pop(4)) 
print(langs)
del langs[:] #tüm elemanları silip boş liste elde ederiz.
print(langs)
del langs
print(langs) #listeyi siler.

['Python', 'Perl']
['PHP', 'Python', 'Lua', 'Perl']
['PHP', 'Python', 'Lua', 'Perl', 'Actionscript', 'Javascript']
Actionscript
['PHP', 'Python', 'Lua', 'Perl', 'Javascript']
[]


NameError: name 'langs' is not defined

In [10]:
import random
class Coin:#coin clasından bir örnek oluşturma(oop)mantığı
    def __init__(self): 
        self.sideup='Heads'
        
    def toss(self):
        if random.randint(0,1) == 0 :
            self.sideup='Heads'
        else:
            self.sideup='Tails'
            
    def get_sideup(self):
        return self.sideup
    #The main function

    
    #Parayı sallama(toss)eylemi
    
    
def main(): 
   my_coin = Coin() #sample
   
   print('This side is up', my_coin.get_sideup())
   print('I am tossing the coin...')
   
   my_coin.toss()
   print('This side is up', my_coin.get_sideup())
 

main()

This side is up Heads
I am tossing the coin...
This side is up Tails


In [2]:
#PYTHON

from numpy import *   #  * --> numpy içindeki tüm fonksiyonları import etmek.(arange fonks.)
import time

In [ ]:
def trad_version():
    t1=time.time()
    X= range(10000000)
    Y= range(10000000)
    Z= []
    for i in range(len(X)):
        Z.append(X[i]+Y[i])
    return time.time()- t1 #yazılan beş satırlık kodun ne kadar zaman aldığını hesaplar.
                

In [38]:
trad_version()

5.9493396282196045

In [39]:
#NUMPY VERSİYONU

def numpy_version():
    t1=time.time() 
    X=arange(10000000) # numpy da range için arange fonksiyonu kullanılır.
    Y=arange(10000000)
    Z=X+Y #python kodundaki gibi for döngüsü gerek yok.
    return time.time()-t1
    

In [40]:
numpy_version() #numpy kodumuz çok daha hızlı!!!

0.07029461860656738

# Numpy 

In [3]:
import numpy as np #np değişkeni üzerinden işlemlerimizi hallederiz.
x=np.array([[1,0,4],[3,3,1]])
y=np.array([[2,5],[1,1],[3,2]])
x.dot(y) #noktasal çarpım
"""
1 0 4    2 5 
3 3 1    1 1 
         3 2

"""

'\n1 0 4    2 5 \n3 3 1    1 1 \n         3 2\n\n'

In [4]:
x=np.array([[1,2,3],[4,5,6]])
type(x) #numpy daki array kavramına ndarray denir.
print(x.shape)
print(x.size) #eleman sayısı
print(x.ndim) #dimension of our array
print(x.dtype) #data type of elements are
print(x.nbytes)

(2, 3)
6
2
int32
24


In [5]:
x=np.array([[1,2,3],[4,5,6]],dtype=np.int64)
print("Int64 consumes",x.nbytes,"bytes")

Int64 consumes 48 bytes


In [6]:
x_copy=np.array(x,dtype=np.float)
x_copy

array([[1., 2., 3.],
       [4., 5., 6.]])

In [7]:
x_copy_int=x_copy.astype(int)
x_copy_int

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
#Array operasyonları
my_list=[2,14,6,8] #python list
my_array=np.asarray(my_list)
my_array

array([ 2, 14,  6,  8])

In [6]:
second_array=np.zeros(4) + 3 #zeros 4 elemanlı her elemanı 0 olan numpy dziisi oluşturdu.
second_array


array([3., 3., 3., 3.])

In [7]:
second_array=np.ones(4) +3
second_array

array([4., 4., 4., 4.])

In [8]:
second_array=np.identity(4)
second_array #identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
a=my_array - second_array
a

array([[ 1., 14.,  6.,  8.],
       [ 2., 13.,  6.,  8.],
       [ 2., 14.,  5.,  8.],
       [ 2., 14.,  6.,  7.]])

In [11]:
b=second_array/ my_array
b

array([[0.5       , 0.        , 0.        , 0.        ],
       [0.        , 0.07142857, 0.        , 0.        ],
       [0.        , 0.        , 0.16666667, 0.        ],
       [0.        , 0.        , 0.        , 0.125     ]])

In [ ]:
#Verilen aralığa göre array oluşturma
x=np.arange(3,7,0.5)
x


In [12]:
x=np.linspace(1.2,40.5,num=20)
x #linear uzayda lineer artan lineer doğru ve noktalar

x=np.geomspace(1,625,num=5)
x #geometrik uzayda 

x=np.logspace(np.log10(3),np.log10(4),num=5)
x
#Farklı uzaylarda array oluşturma


array([3.        , 3.2237098 , 3.46410162, 3.72241944, 4.        ])

In [13]:
x=np.array([1,2,3,4])
x=np.array([1,3,4,4])
x==y


<ipython-input-13-fa2aeacd5e73>:3: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  x==y


False

In [14]:
#Logical or operatörü diziler
x=np.array([0,1,0,0],dtype=bool) #mutable olduğundan type ını belirttik.
y=np.array([1,1,0,1],dtype=bool) #bool yazmasam da T/F olarak atadı.
z=np.logical_or(x,y)
z 

array([ True,  True, False,  True])

In [15]:
#Logical and operatörü diziler
x=np.array([0,1,0,0],dtype=bool) #mutable olduğundan type ını belirttik.
y=np.array([1,1,0,1],dtype=bool) #bool yazmasam da T/F olarak atadı.
z=np.logical_and(x,y)
z 

array([False,  True, False, False])

In [22]:
x=np.array([12,16,57,11])
y=np.logical_or(x<13 ,x>50)
y

array([ True, False,  True,  True])

In [15]:
#Transcendental fonksiyonlar
x=np.array([1,2,3,4])
y=np.exp(x)
y  #e^1,e^2,e^3,e^4

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [16]:
z=np.log(x)
z #log1,log2,log3,log4

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [17]:
t=np.sin(x)
t

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

# Array yeniden şekilllendirme(reshaping)


In [23]:
x=np.arange(9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [24]:
x=np.arange(9).reshape((3,3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
y=np.arange(6).reshape(2,3)
y

array([[0, 1, 2],
       [3, 4, 5]])

In [26]:
y.T #transpoze almak.

array([[0, 3],
       [1, 4],
       [2, 5]])

In [27]:
#Temel İstatistik
a=np.sum(x)
a

36

In [28]:
b=np.amin(x)
b #numpy dizimdeki min sayı

0

In [29]:
c=np.amax(x)
c

8

In [27]:
d=np.amin(x,axis=0)
d

array([0, 1, 2])

In [28]:
e=np.amin(x,axis=1)
e

array([0, 3, 6])

In [29]:
x=np.array([1,-21,3,-3])
y=np.argmax(x) #dizindeki değeri maks olan değerin indeksi
y

2

In [30]:
z=np.argmin(x) #dizindeki değeri min olan  değerin indeksi
z

1

In [32]:
x=np.array([[2,3,5],[20,12,4]])
x

array([[ 2,  3,  5],
       [20, 12,  4]])

In [33]:
ort=np.mean(x)
ort

7.666666666666667

In [34]:
ort0=np.mean(x,axis=0)
ort0

array([11. ,  7.5,  4.5])

In [35]:
ort1=np.mean(x,axis=1)
ort1

array([ 3.33333333, 12.        ])

In [36]:
median=np.median(x)
median

4.5

In [37]:
stdsapma=np.std(x)
stdsapma

6.394442031083626

Çok boyutlu dizilerle çalışmak için
* yerine dot() fonksiyonunu kullanılır.


In [39]:
c=np.ones((4,4))
c*c #yanlış sonuç yani çok boyutlu dzilerde * kullanılmaz.

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [40]:
c.dot(c) #doğru sonuç

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [ ]:
#ÇOk boyutlu array birleştirme

In [41]:
y=np.arange(15).reshape(3,5)
x=np.arange(10).reshape(2,5)
new_array=np.vstack((y,x)) #vertical stack
new_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

In [42]:
y=np.arange(15).reshape(5,3)
x=np.arange(10).reshape(5,2)
new_array=np.hstack((y,x)) #horizontal stack
new_array

array([[ 0,  1,  2,  0,  1],
       [ 3,  4,  5,  2,  3],
       [ 6,  7,  8,  4,  5],
       [ 9, 10, 11,  6,  7],
       [12, 13, 14,  8,  9]])

In [43]:
#maskeleme ve geçersiz kalma
import numpy.ma as ma #import

In [45]:
x=np.arange(6) #[0,1,2,3,4,5]
print(x.mean()) #mean
masked_array=ma.masked_array(x,mask=[1,0,0,0,0,0])
masked_array.mean() #[__,1,2,3,4,5]

2.5


3.0

In [46]:
x=np.arange(25,dtype=float).reshape(5,5)
x[x<5]=np.nan #5 ten küçük indisler nan(not a number)
x

array([[nan, nan, nan, nan, nan],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

#homework
np.where(np.isnan(x),ma.array(x,mask=np.isnan(x)).mean(axis=0),x)

# indexing,slicing,reshaping and resizing

In [30]:
#indexing
x=np.arange(10)
x
x[2:8:2]

array([2, 4, 6])

In [31]:
#slicing
x=np.reshape(np.arange(16),(4,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [52]:
x[1:3]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [53]:
x[:,1:3] # x de hepsini al y de 1:3

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [54]:
x[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [55]:
#reshaping
x=np.reshape(np.arange(16),(4,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [56]:
x[[0,1,2],[0,1,3]] #0,0  1,1   2,3

array([ 0,  5, 11])

In [9]:
a=np.resize(x,(2,2))
a

array([[1, 2],
       [3, 4]], dtype=int64)

In [10]:
b=np.resize(x,(6,6))
b

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]], dtype=int64)

Keşifsel Veri Analizi(Exploratory Data Analysis)
.Veri setlerini istatistiksel olarak analiz etme.
..Dosya yükleme ve saklama.
..Veri setini keşfetme.
..Temel istatistiğe ayrıntılı bakış.
..Histogram hesaplama,box plot çizdirme.
SciPy,Pandas(veri manipülasyonu,reshaping)kütüphanelerinden yararlanılır.
.Sci-Kit Learn yapay öğrenme algoritmalarını kullandığımız toolbox.

# DOSYA KAYDETME

In [3]:
import numpy as np

In [4]:
example_array=np.arange(12).reshape(3,4)
example_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
np.save('example.npy',example_array)
d=np.load('example.npy')
np.shape(d)
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
data=np.genfromtxt("myfile.txt",skip_header=1) #genfromtxt-skip_header
data 

array([[10., 11., 12., 13., 14., 15., 16., 17., 18.],
       [29., 20., 21., 22., 23., 24., 25., 26., 27.],
       [28., 29., 30., 31., 32., 33., 34., 35., 36.],
       [37., 38., 39., 40., 41., 42., 43., 44., 45.]])

In [7]:
data1=np.loadtxt("myfile.txt",skiprows=1) #loadtxt-skiprows
data1

array([[10., 11., 12., 13., 14., 15., 16., 17., 18.],
       [29., 20., 21., 22., 23., 24., 25., 26., 27.],
       [28., 29., 30., 31., 32., 33., 34., 35., 36.],
       [37., 38., 39., 40., 41., 42., 43., 44., 45.]])

In [8]:
from sklearn.datasets import load_boston


In [9]:
dataset=load_boston()
dataset

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 3

In [25]:
from sklearn.datasets import load_boston
dataset=load_boston()
samples,label,feature_names=dataset.data,dataset.target,dataset.feature_names

In [10]:
samples=dataset.data
samples

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [11]:
label=dataset.target
dataset #veri etiketleri


{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 3

In [12]:
feature_names=dataset.feature_names
feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [13]:
label.shape

(506,)

In [14]:
print(dataset.DESCR)

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

In [15]:
#univariate analysis-özellikleri tek tek keşfetme
a=np.set_printoptions(suppress=True,linewidth=125)
a

In [16]:
minimums=np.round(np.amin(samples,axis=0),decimals=1)
minimums #Veri setinin verilerinden


array([  0. ,   0. ,   0.5,   0. ,   0.4,   3.6,   2.9,   1.1,   1. , 187. ,  12.6,   0.3,   1.7])

In [17]:
maximums=np.round(np.amax(samples,axis=0),decimals=1)
maximums

array([ 89. , 100. ,  27.7,   1. ,   0.9,   8.8, 100. ,  12.1,  24. , 711. ,  22. , 396.9,  38. ])

In [18]:
range_column=np.round(np.ptp(samples,axis=0),decimals=1)
range_column

array([ 89. , 100. ,  27.3,   1. ,   0.5,   5.2,  97.1,  11. ,  23. , 524. ,   9.4, 396.6,  36.2])

In [20]:
mean=np.round(np.mean(samples,axis=0),decimals=1)
median=np.round(np.median(samples,axis=0),decimals=1)
variance=np.round(np.var(samples,axis=0),decimals=1)

In [21]:
mean,median,variance

(array([  3.6,  11.4,  11.1,   0.1,   0.6,   6.3,  68.6,   3.8,   9.5, 408.2,  18.5, 356.7,  12.7]),
 array([  0.3,   0. ,   9.7,   0. ,   0.5,   6.2,  77.5,   3.2,   5. , 330. ,  19. , 391.4,  11.4]),
 array([   73.8,   542.9,    47. ,     0.1,     0. ,     0.5,   790.8,     4.4,    75.7, 28348.6,     4.7,  8318.3,    50.9]))

In [64]:
from scipy import stats
arr=stats.describe(samples,axis=0)
arr

DescribeResult(nobs=506, minmax=(array([  0.00632,   0.     ,   0.46   ,   0.     ,   0.385  ,   3.561  ,   2.9    ,   1.1296 ,   1.     , 187.     ,
        12.6    ,   0.32   ,   1.73   ]), array([ 88.9762, 100.    ,  27.74  ,   1.    ,   0.871 ,   8.78  , 100.    ,  12.1265,  24.    , 711.    ,  22.    ,
       396.9   ,  37.97  ])), mean=array([  3.61352356,  11.36363636,  11.13677866,   0.06916996,   0.55469506,   6.28463439,  68.57490119,   3.79504269,
         9.54940711, 408.23715415,  18.4555336 , 356.67403162,  12.65306324]), variance=array([   73.9865782 ,   543.93681368,    47.06444247,     0.06451297,     0.01342764,     0.49367085,   792.35839851,
           4.43401514,    75.81636598, 28404.75948812,     4.68698912,  8334.75226292,    50.99475951]), skewness=array([ 5.20765239,  2.21906306,  0.29414628,  3.39579929,  0.72714416,  0.40241467, -0.59718559,  1.00877876,  1.00183349,
        0.66796827, -0.79994453, -2.88179835,  0.90377074]), kurtosis=array([36.75278626,  3

In [65]:
Basic_Statistics=np.vstack((minimums,maximums,range_column,mean,median,variance))
Basic_Statistics

array([[    0. ,     0. ,     0.5,     0. ,     0.4,     3.6,     2.9,     1.1,     1. ,   187. ,    12.6,     0.3,
            1.7],
       [   89. ,   100. ,    27.7,     1. ,     0.9,     8.8,   100. ,    12.1,    24. ,   711. ,    22. ,   396.9,
           38. ],
       [   89. ,   100. ,    27.3,     1. ,     0.5,     5.2,    97.1,    11. ,    23. ,   524. ,     9.4,   396.6,
           36.2],
       [    3.6,    11.4,    11.1,     0.1,     0.6,     6.3,    68.6,     3.8,     9.5,   408.2,    18.5,   356.7,
           12.7],
       [    0.3,     0. ,     9.7,     0. ,     0.5,     6.2,    77.5,     3.2,     5. ,   330. ,    19. ,   391.4,
           11.4],
       [   73.8,   542.9,    47. ,     0.1,     0. ,     0.5,   790.8,     4.4,    75.7, 28348.6,     4.7,  8318.3,
           50.9]])

In [24]:
stat_labels=['minm','maxm','rang','mean','medi','vari']

Pandas 

In [25]:
import pandas as pd
import numpy as np
import warnings

warnings.filterwarnings('ignore') #uyarıları filtreleme

In [26]:
#({}) yapısını unutma.
df= pd.DataFrame({'Ad':['İstanbul','Ankara','İzmir','Bursa','Antalya'],'Nüfus':[153683,43247498,34242521,3141432,342141],'Kod':['32','32','12','45','34'] })

In [27]:
df


Ad     Nüfus Kod
0  İstanbul    153683  32
1    Ankara  43247498  32
2     İzmir  34242521  12
3     Bursa   3141432  45
4   Antalya    342141  34

In [28]:
# iki boyutlu dataframe

In [60]:
dizi=np.array([[0,1,2,3],[4,5,6,7]])
df=pd.DataFrame(dizi)
df

0  1  2  3
0  0  1  2  3
1  4  5  6  7

In [61]:
df.columns=['Kolon1','Kolon2','Kolon3','Kolon4']
df.index=['Satır1','Satır2']
df

Kolon1  Kolon2  Kolon3  Kolon4
Satır1       0       1       2       3
Satır2       4       5       6       7

In [66]:
df2=pd.DataFrame(dizi,columns)=['Kolon1','Kolon2','Kolon3','Kolon4'],index=['Satır1','Satır2']
df2()

SyntaxError: cannot assign to function call (<ipython-input-66-a2e3d3798883>, line 1)

In [67]:
ulke_kod=['FR','GE','US','UK','CN']
ulkeler=pd.DataFrame(index=ulke_kod)
ulkeler.index.name='Kod'
ulkeler

Empty DataFrame
Columns: []
Index: [FR, GE, US, UK, CN]

In [68]:
ulkeler['Ulke']=['Fransa','Almanya','ABD','İngiltere','Çİn']
ulkeler['Nüfus']=[3183719,24309840,309849032,29348920,238490384]
ulkeler['Yaşam Süresi']=[45.423,43.34,78.45,65.89,83.54]
ulkeler['Toplam Gelir']=[342834098340,480489,50986904,4580388750,3589442]
ulkeler['Kıta']=['Avrupa','Avrupa','Amerika','Avrupa','Asya']

In [69]:
print(ulkeler.Nüfus)
print(ulkeler['Nüfus'])

Kod
FR      3183719
GE     24309840
US    309849032
UK     29348920
CN    238490384
Name: Nüfus, dtype: int64
Kod
FR      3183719
GE     24309840
US    309849032
UK     29348920
CN    238490384
Name: Nüfus, dtype: int64


In [39]:
ulkeler['Kişi_Bası_Gelir']=(ulkeler['Toplam Gelir']/ulkeler['Nüfus']).astype(int)
ulkeler

Ulke        Nüfus  Yaşam Süresi  Toplam Gelir     Kıta  \
Kod                                                                
FR      Fransa      3183719        45.423  342834098340   Avrupa   
GE     Almanya     24309840        43.340        480489   Avrupa   
US         ABD    309849032        78.450      50986904  Amerika   
UK   İngiltere     29348920        65.890    4580388750   Avrupa   
CN         Çİn  23849902384        83.540       3589442     Asya   

     Kişi_Bası_Gelir  
Kod                   
FR            107683  
GE                 0  
US                 0  
UK               156  
CN                 0

In [45]:
ulkeler['Toplam Gelir']/ulkeler['Nüfus']

Kod
FR    107683.529338
GE         0.019765
US         0.164554
UK       156.066688
CN         0.000151
dtype: float64

In [46]:
ulkeler.loc['GE'] #ÜLKENİN BİLGİSİNİ GETİRME

Ulke                Almanya
Nüfus              24309840
Yaşam Süresi          43.34
Toplam Gelir         480489
Kıta                 Avrupa
Kişi_Bası_Gelir           0
Name: GE, dtype: object

In [47]:
ulkeler.iloc[1:3,1:4]

Nüfus  Yaşam Süresi  Toplam Gelir
Kod                                       
GE    24309840         43.34        480489
US   309849032         78.45      50986904

In [52]:
ulkeler.loc[lambda df:ulkeler['Nüfus']>100000000,:] #ülkenin bilgisini getiren fonksiyon

Ulke        Nüfus  Yaşam Süresi  Toplam Gelir     Kıta  Kişi_Bası_Gelir
Kod                                                                        
US   ABD    309849032         78.45      50986904  Amerika                0
CN   Çİn  23849902384         83.54       3589442     Asya                0

In [51]:
ulkeler[ulkeler['Nüfus']>100000000] #lambda fonksiyonunu kullanmadan gösterimi

Ulke        Nüfus  Yaşam Süresi  Toplam Gelir     Kıta  Kişi_Bası_Gelir
Kod                                                                        
US   ABD    309849032         78.45      50986904  Amerika                0
CN   Çİn  23849902384         83.54       3589442     Asya                0

In [54]:
# ulkeler.groupby('Kıta') error
ulkeler.groupby(by='Kıta').mean()['Kişi_Bası_Gelir']

Kıta
Amerika        0.000000
Asya           0.000000
Avrupa     35946.333333
Name: Kişi_Bası_Gelir, dtype: float64

In [55]:
ulkeler.groupby(by='Kıta').sum()['Nüfus'] #


Kıta
Amerika      309849032
Asya       23849902384
Avrupa        56842479
Name: Nüfus, dtype: int64

PANDAS ÇERÇEVELERİNİ BİRBİRİNE BAĞLAMA

In [56]:
ulkeler=pd.DataFrame({'Ulke':['Japonya','Fransa']},index=['JP','FR'])
baskentler=pd.DataFrame({'Baskent':['Tokyo','Paris']},index=['JP','FR'])
ulke_baskentleri=pd.concat([ulkeler,baskentler],axis=1)
ulke_baskentleri

Ulke Baskent
JP  Japonya   Tokyo
FR   Fransa   Paris

In [74]:
#çerçeveleri birbiriyle birleştirme
ulkeler=pd.DataFrame({'Ulke':['Japonya','Fransa','Almanya'],'Kıta':['Asya','Avrupa','Avrupa']})
baskentler=pd.DataFrame({'Ad':['Fransa','Japonya','Almanya'],'Baskent':['Paris','Tokya','Berlin']})

pd.merge(ulkeler,baskentler,left_on='Ulke',right_on='Ad')


Ulke    Kıta       Ad Baskent
0  Japonya    Asya  Japonya   Tokya
1   Fransa  Avrupa   Fransa   Paris
2  Almanya  Avrupa  Almanya  Berlin

In [80]:
import pandas as pd
df=pd.read_csv('train.csv')
df

FileNotFoundError: [Errno 2] File train.csv does not exist: 'train.csv'